#!/usr/bin/env python3
"""Generate policy/operations.json from the corrected Replicant Space contract.

Reads reference/replicant-space/openapi.json for the full operation set and
classifies each operation as supported, deprecated, or admin using the
guide-locked exclusion list (rewrite-guide.md section 5). The OpenAPI schema
does not set `deprecated: true` on any operation; the five deprecated
operations are identified only by rendered documentation asides, which this
guide records as authoritative over missing OpenAPI flags.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OPENAPI = ROOT / "reference" / "replicant-space" / "openapi.json"
OUT = ROOT / "policy" / "operations.json"

# (method, path) -> (reason, evidence file relative to reference/replicant-space)
DEPRECATED = {
    ("GET", "/v1/accounts/webhook"): (
        "Webhook system is deprecated in favour of the account event stream "
        "and message subscriptions; existing webhooks continue to work but "
        "are phased out.",
        "api/accounts/webhook/index.md",
    ),
    ("POST", "/v1/accounts/webhook"): (
        "Webhook system is deprecated in favour of the account event stream "
        "and message subscriptions; existing webhooks continue to work but "
        "are phased out.",
        "api/accounts/webhook/index.md",
    ),
    ("DELETE", "/v1/accounts/webhook"): (
        "Webhook system is deprecated in favour of the account event stream "
        "and message subscriptions; existing webhooks continue to work but "
        "are phased out.",
        "api/accounts/webhook/index.md",
    ),
    ("GET", "/v1/replicants/{replicant_code}/events"): (
        "Per-replicant event log is deprecated in favour of the unified "
        "account event stream, which covers all replicants in real time.",
        "api/replicants/events/index.md",
    ),
    ("GET", "/v1/locations/{designation}/inventory"): (
        "Legacy per-location inventory endpoint is deprecated in favour of "
        "the account-wide GET /v1/inventory endpoint.",
        "api/locations/inventory/index.md",
    ),
}

ADMIN = {
    ("POST", "/v1/admin/message"): (
        "Administrative broadcast endpoint under /v1/admin; excluded from a "
        "player-facing client.",
        "openapi.json",
    ),
    ("POST", "/v1/admin/story/advance"): (
        "Administrative story-advancement endpoint under /v1/admin; "
        "excluded from a player-facing client.",
        "openapi.json",
    ),
}

METHODS = {"get", "post", "put", "patch", "delete"}


def schema_type(schema: dict | None) -> str:
    if not schema:
        return "none"
    if reference := schema.get("$ref"):
        return reference.rsplit("/", 1)[-1]
    return schema.get("type", "inline")


def content_schema(content: dict | None) -> dict | None:
    return (content or {}).get("application/json", {}).get("schema")


def response_type(responses: dict) -> str:
    for status, response in responses.items():
        if status.startswith("2"):
            return schema_type(content_schema(response.get("content")))
    return "none"


def build_inventory(spec: dict) -> dict:
    paths = spec["paths"]

    operations = []
    for path, methods in paths.items():
        for method, op in methods.items():
            if method.lower() not in METHODS:
                continue
            key = (method.upper(), path)
            entry = {
                "method": key[0],
                "path": key[1],
                "operation_id": op.get("operationId"),
                "auth_required": bool(op.get("security", spec.get("security", []))),
                "safety": "safe_read" if key[0] in {"GET", "HEAD"} else "mutating",
                "request_type": schema_type(content_schema(op.get("requestBody", {}).get("content"))),
                "response_type": response_type(op.get("responses", {})),
            }
            if key in DEPRECATED:
                reason, evidence = DEPRECATED[key]
                entry["classification"] = "deprecated"
                entry["reason"] = reason
                entry["evidence"] = evidence
            elif key in ADMIN:
                reason, evidence = ADMIN[key]
                entry["classification"] = "admin"
                entry["reason"] = reason
                entry["evidence"] = evidence
            else:
                entry["classification"] = "supported"
            operations.append(entry)

    operations.sort(key=lambda e: (e["path"], e["method"]))

    supported = [o for o in operations if o["classification"] == "supported"]
    deprecated = [o for o in operations if o["classification"] == "deprecated"]
    admin = [o for o in operations if o["classification"] == "admin"]

    return {
        "$schema_note": (
            "Machine-readable Replicant Space 2.4.0 operation inventory. "
            "Generated by scripts/generate_operation_inventory.py from "
            "reference/replicant-space/openapi.json plus rendered "
            "documentation deprecation asides."
        ),
        "totals": {
            "total_operations": len(operations),
            "supported": len(supported),
            "deprecated": len(deprecated),
            "admin": len(admin),
            "excluded": len(deprecated) + len(admin),
        },
        "operations": operations,
    }


def main() -> None:
    spec = json.loads(OPENAPI.read_text())
    doc = build_inventory(spec)
    OUT.write_text(json.dumps(doc, indent=2, sort_keys=False) + "\n")
    t = doc["totals"]
    print(f"wrote {OUT} ({t['total_operations']} operations, "
          f"{t['supported']} supported, {t['deprecated']} deprecated, "
          f"{t['admin']} admin)")


if __name__ == "__main__":
    main()
